sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - trained

dist: trusty
language: python

python:
  - "2.7"
install: source continuous_integration/install.sh
script: python -m unittest tests.basic