language: python
python:
  - "2.7"
install:
  - sudo apt-get install -y libblas-dev liblapack-dev
  - pip uninstall boto
  - pip install boto
  - pip install -r requirements.txt
  - cd trained
  - python download.py
  - cd ..
  - python manage.py create_table
script: python -m unittest tests.basic